In [75]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns # visualize
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)

In [76]:
st_math = pd.read_csv('student-mat.csv', header = 0)
st_port = pd.read_csv('student-por.csv', header = 0)

In [77]:
frames = [st_math, st_port]

### Criar a coluna boolean `type`
* 0 = matemática
* 1 = português

In [78]:
st_math['school_subject'] = 0
st_port['school_subject'] = 1

In [79]:
st_math.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,school_subject
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,6,5,6,6,0
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,4,5,5,6,0
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,3,yes,no,yes,no,yes,yes,yes,no,4,3,2,2,3,3,10,7,8,10,0
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,yes,yes,yes,yes,yes,yes,3,2,2,1,1,5,2,15,14,15,0
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,yes,no,yes,yes,no,no,4,3,2,1,2,5,4,6,10,10,0

In [80]:
st_port.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,school_subject
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,4,0,11,11,1
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,2,9,11,11,1
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,0,yes,no,no,no,yes,yes,yes,no,4,3,2,2,3,3,6,12,13,12,1
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,no,yes,yes,yes,yes,yes,3,2,2,1,1,5,0,14,14,14,1
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,no,no,yes,yes,no,no,4,3,2,1,2,5,0,11,13,13,1

### Criar coluna `is_approved`  

Conforme falamos, vamos criar uma nova coluna de aprovação x reprovação.

Eu considerei a média da escola para definir se o aluno estaria aprovado ou reprovado.

In [81]:
for dataset in frames:
    ave = sum(dataset.G3)/float(len(dataset))
    dataset['is_approved'] = [1 if i > ave else 0 for i in dataset.G3]

In [82]:
st_math.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,school_subject,is_approved
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,6,5,6,6,0,0
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,4,5,5,6,0,0
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,3,yes,no,yes,no,yes,yes,yes,no,4,3,2,2,3,3,10,7,8,10,0,0
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,yes,yes,yes,yes,yes,yes,3,2,2,1,1,5,2,15,14,15,0,1
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,yes,no,yes,yes,no,no,4,3,2,1,2,5,4,6,10,10,0,0

In [83]:
st_port.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3,school_subject,is_approved
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,4,0,11,11,1,0
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,2,9,11,11,1,0
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,0,yes,no,no,no,yes,yes,yes,no,4,3,2,2,3,3,6,12,13,12,1,1
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,no,yes,yes,yes,yes,yes,3,2,2,1,1,5,0,14,14,14,1,1
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,no,no,yes,yes,no,no,4,3,2,1,2,5,0,11,13,13,1,1

### Criar um novo dataframe `dataset` que compila as duas bases

In [86]:
frames = [st_math, st_port]
dataset = pd.concat(frames, sort=False)
print("Length result dataset: {} rows".format(len(dataset)))

Length result dataset: 1044 rows

### Remover as colunas `G1` e `G2` e criar coluna `is_approved`  

Conforme, falamos não vamos utilizar G1, G2 e G3 no modelo, mas vamos criar uma nova coluna de aprovação x reprovação.

In [87]:
deleted_columns = ['G1', 'G2', 'G3']
for c in deleted_columns:
    del dataset[c]

In [88]:
dataset.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,reason,guardian,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,school_subject,is_approved
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,course,mother,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,6,0,0
1,GP,F,17,U,GT3,T,1,1,at_home,other,course,father,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,4,0,0
2,GP,F,15,U,LE3,T,1,1,at_home,other,other,mother,1,2,3,yes,no,yes,no,yes,yes,yes,no,4,3,2,2,3,3,10,0,0
3,GP,F,15,U,GT3,T,4,2,health,services,home,mother,1,3,0,no,yes,yes,yes,yes,yes,yes,yes,3,2,2,1,1,5,2,0,1
4,GP,F,16,U,GT3,T,3,3,other,other,home,father,1,2,0,no,yes,yes,no,yes,yes,no,no,4,3,2,1,2,5,4,0,0

In [89]:
dataset.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'school_subject', 'is_approved'],
      dtype='object')

### Aplicar one-hot enconding nas colunas 

`'Medu','Fedu','Mjob','Fjob','reason','guardian'`

In [90]:
# converter para binário
one_hot_columns = ['Medu','Fedu','Mjob','Fjob','reason','guardian']

In [91]:
dataset = dataset.copy()
dataset = pd.get_dummies(dataset, columns=['Medu','Fedu','Mjob','Fjob','reason','guardian'], prefix = ['Medu','Fedu','Mjob','Fjob','reason','guardian'])

In [92]:
dataset.head()

,school,sex,age,address,famsize,Pstatus,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,school_subject,is_approved,Medu_0,Medu_1,Medu_2,Medu_3,Medu_4,Fedu_0,Fedu_1,Fedu_2,Fedu_3,Fedu_4,Mjob_at_home,Mjob_health,Mjob_other,Mjob_services,Mjob_teacher,Fjob_at_home,Fjob_health,Fjob_other,Fjob_services,Fjob_teacher,reason_course,reason_home,reason_other,reason_reputation,guardian_father,guardian_mother,guardian_other
0,GP,F,18,U,GT3,A,2,2,0,yes,no,no,no,yes,yes,no,no,4,3,4,1,1,3,6,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0
1,GP,F,17,U,GT3,T,1,2,0,no,yes,no,no,no,yes,yes,no,5,3,3,1,1,3,4,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0
2,GP,F,15,U,LE3,T,1,2,3,yes,no,yes,no,yes,yes,yes,no,4,3,2,2,3,3,10,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0
3,GP,F,15,U,GT3,T,1,3,0,no,yes,yes,yes,yes,yes,yes,yes,3,2,2,1,1,5,2,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0
4,GP,F,16,U,GT3,T,1,2,0,no,yes,yes,no,yes,yes,no,no,4,3,2,1,2,5,4,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,0

### Converter de nominal para binário

In [93]:
print("school: " , dataset.school.unique())
print("sex: " , dataset.sex.unique())
print("address: " , dataset.address.unique())
print("famsize: " , dataset.famsize.unique())
print("schoolsup: " , dataset.schoolsup.unique())
print("famsup: " , dataset.famsup.unique())
print("paid: " , dataset.paid.unique())
print("activities: " , dataset.activities.unique())
print("nursery: " , dataset.nursery.unique())
print("higher: " , dataset.higher.unique())
print("internet: " , dataset.internet.unique())
print("romantic: " , dataset.romantic.unique())
print("Pstatus: " , dataset.Pstatus.unique())

school:  ['GP' 'MS']
sex:  ['F' 'M']
address:  ['U' 'R']
famsize:  ['GT3' 'LE3']
schoolsup:  ['yes' 'no']
famsup:  ['no' 'yes']
paid:  ['no' 'yes']
activities:  ['no' 'yes']
nursery:  ['yes' 'no']
higher:  ['yes' 'no']
internet:  ['no' 'yes']
romantic:  ['no' 'yes']
Pstatus:  ['A' 'T']

In [94]:
dataset['school'] = dataset['school'].map( {'GP': 0, 'MS': 1} ).astype(int)
dataset['sex'] = dataset['sex'].map( {'F': 0, 'M': 1} ).astype(int)
dataset['address'] = dataset['address'].map( {'U': 0, 'R': 1} ).astype(int)
dataset['famsize'] = dataset['famsize'].map( {'GT3': 0, 'LE3': 1}).astype(int)
dataset['Pstatus'] = dataset['Pstatus'].map( {'A': 0, 'T': 1}).astype(int)

In [95]:
binary_columns = ['schoolsup', 'famsup', 'paid', 'activities', 'nursery','higher', 'internet', 'romantic']

for c in binary_columns:
    dataset[c] = dataset[c].map( {'yes': 1, 'no': 0} ).astype(int)

In [96]:
dataset.head(15)

,school,sex,age,address,famsize,Pstatus,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,school_subject,is_approved,Medu_0,Medu_1,Medu_2,Medu_3,Medu_4,Fedu_0,Fedu_1,Fedu_2,Fedu_3,Fedu_4,Mjob_at_home,Mjob_health,Mjob_other,Mjob_services,Mjob_teacher,Fjob_at_home,Fjob_health,Fjob_other,Fjob_services,Fjob_teacher,reason_course,reason_home,reason_other,reason_reputation,guardian_father,guardian_mother,guardian_other
0,0,0,18,0,0,0,2,2,0,1,0,0,0,1,1,0,0,4,3,4,1,1,3,6,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,1,0
1,0,0,17,0,0,1,1,2,0,0,1,0,0,0,1,1,0,5,3,3,1,1,3,4,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0
2,0,0,15,0,1,1,1,2,3,1,0,1,0,1,1,1,0,4,3,2,2,3,3,10,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0
3,0,0,15,0,0,1,1,3,0,0,1,1,1,1,1,1,1,3,2,2,1,1,5,2,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0
4,0,0,16,0,0,1,1,2,0,0,1,1,0,1,1,0,0,4,3,2,1,2,5,4,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,1,0,0
5,0,1,16,0,1,1,1,2,0,0,1,1,1,1,1,1,0,5,4,2,1,2,5,10,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,1,0
6,0,1,16,0,1,1,1,2,0,0,0,0,0,1,1,1,0,4,4,4,1,1,3,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0
7,0,0,17,0,0,0,2,2,0,1,1,0,0,1,1,0,0,4,1,4,1,1,1,6,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,0
8,0,1,15,0,1,0,1,2,0,0,1,1,0,1,1,1,0,4,2,2,1,1,1,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0
9,0,1,15,0,0,1,1,2,0,0,1,1,1,1,1,1,0,5,5,1,1,1,5,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0
10,0,0,15,0,0,1,1,2,0,0,1,1,0,1,1,1,0,3,3,3,1,2,2,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0
11,0,0,15,0,0,1,3,3,0,0,1,0,1,1,1,1,0,5,2,2,1,1,4,4,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,1,0,0
12,0,1,15,0,1,1,1,1,0,0,1,1,1,1,1,1,0,4,3,3,1,3,5,2,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0
13,0,1,15,0,0,1,2,2,0,0,1,1,0,1,1,1,0,5,4,3,1,2,3,2,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0
14,0,1,15,0,0,0,1,3,0,0,1,0,0,1,1,1,1,4,5,2,1,1,3,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1

### Aplicar min-max nas colunas

In [98]:
from sklearn import preprocessing

x = dataset.values #returns a numpy array

min_max_scaler = preprocessing.MinMaxScaler()

x_scaled = min_max_scaler.fit_transform(x)

df = pd.DataFrame(x_scaled, columns=['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'traveltime','studytime', 'failures', 'schoolsup', 'famsup', 'paid', 'activities','nursery', 'higher', 'internet', 'romantic', 'famrel', 'freetime','goout', 'Dalc', 'Walc', 'health', 'absences','school_subject','is_approved', 'Medu_0', 'Medu_1', 'Medu_2', 'Medu_3', 'Medu_4','Fedu_0', 'Fedu_1', 'Fedu_2', 'Fedu_3', 'Fedu_4', 'Mjob_at_home', 'Mjob_health', 'Mjob_other', 'Mjob_services', 'Mjob_teacher', 'Fjob_at_home', 'Fjob_health', 'Fjob_other', 'Fjob_services',       'Fjob_teacher', 'reason_course', 'reason_home', 'reason_other',      'reason_reputation', 'guardian_father', 'guardian_mother',    'guardian_other'])

### Temos um novo dataset normalizado: `df`

In [100]:
df.head(30)

,school,sex,age,address,famsize,Pstatus,traveltime,studytime,failures,schoolsup,famsup,paid,activities,nursery,higher,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,school_subject,is_approved,Medu_0,Medu_1,Medu_2,Medu_3,Medu_4,Fedu_0,Fedu_1,Fedu_2,Fedu_3,Fedu_4,Mjob_at_home,Mjob_health,Mjob_other,Mjob_services,Mjob_teacher,Fjob_at_home,Fjob_health,Fjob_other,Fjob_services,Fjob_teacher,reason_course,reason_home,reason_other,reason_reputation,guardian_father,guardian_mother,guardian_other
0,0.0,0.0,0.428571,0.0,0.0,0.0,0.333333,0.333333,0.000000,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.75,0.50,0.75,0.00,0.00,0.50,0.080000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.285714,0.0,0.0,1.0,0.000000,0.333333,0.000000,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.00,0.50,0.50,0.00,0.00,0.50,0.053333,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
2,0.0,0.0,0.000000,0.0,1.0,1.0,0.000000,0.333333,1.000000,1.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.75,0.50,0.25,0.25,0.50,0.50,0.133333,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.000000,0.0,0.0,1.0,0.000000,0.666667,0.000000,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.50,0.25,0.25,0.00,0.00,1.00,0.026667,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.142857,0.0,0.0,1.0,0.000000,0.333333,0.000000,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.75,0.50,0.25,0.00,0.25,1.00,0.053333,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
5,0.0,1.0,0.142857,0.0,1.0,1.0,0.000000,0.333333,0.000000,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.00,0.75,0.25,0.00,0.25,1.00,0.133333,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
6,0.0,1.0,0.142857,0.0,1.0,1.0,0.000000,0.333333,0.000000,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.75,0.75,0.75,0.00,0.00,0.50,0.000000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
7,0.0,0.0,0.285714,0.0,0.0,0.0,0.333333,0.333333,0.000000,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.75,0.00,0.75,0.00,0.00,0.00,0.080000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
8,0.0,1.0,0.000000,0.0,1.0,0.0,0.000000,0.333333,0.000000,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.75,0.25,0.25,0.00,0.00,0.00,0.000000,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
9,0.0,1.0,0.000000,0.0,0.0,1.0,0.000000,0.333333,0.000000,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.00,1.00,0.00,0.00,0.00,1.00,0.000000,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
10,0.0,0.0,0.000000,0.0,0.0,1.0,0.000000,0.333333,0.000000,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.50,0.50,0.50,0.00,0.25,0.25,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
11,0.0,0.0,0.000000,0.0,0.0,1.0,0.666667,0.666667,0.000000,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.00,0.25,0.25,0.00,0.00,0.75,0.053333,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
12,0.0,1.0,0.000000,0.0,1.0,1.0,0.000000,0.000000,0.000000,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.75,0.50,0.50,0.00,0.50,1.00,0.026667,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
13,0.0,1.0,0.000000,0.0,0.0,1.0,0.333333,0.333333,0.000000,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.00,0.75,0.50,0.00,0.25,0.50,0.026667,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
14,0.0,1.0,0.000000,0.0,0.0,0.0,0.000000,0.666667,0.000000,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.75,1.00,0.25,0.00,0.00,0.50,0.000000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
15,0.0,0.0,0.142857,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.75,0.75,0.75,0.00,0.25,0.25,0.053333,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
16,0.0,0.0,0.142857,0.0,0.0,1.0,0.000000,0.666667,0.000000,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.50,0.25,0.50,0.00,0.25,0.25,0.080000,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
17,0.0,0.0,0.142857,0.0,0.0,1.0,0.666667,0.333333,0.000000,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,1.00,0.50,0.25,0.00,0.00,0.75,0.053333,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
18,0.0,1.0,0.285714,0.0,0.0,1.0,0.000000,0.000000,1.000000,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.00,1.00,1.00,0.25,0.75,1.00,0.213333,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
19,0.0,1.0,0.142857,0.0,1.0,1.0,0.000000,0.000000,0.000000,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.50,0.00,0.50,0.00,0.50,1.00,0.053333,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
20,0.0,1.0,0.000000,0.0,0.0,1.0,0.000000,0.333333,0.000000,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.75,0.75,0.00,0.00,0.00,0.00,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
21,0.0,1.0,0.000000,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.00,0.75,0.25,0.00,0.00,1.00,0.000000,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
22,0.0,1.0,0.142857,0.0,1.0,1.0,0.000000,0.333333,0.000000,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.75,1.00,0.00,0.00,0.50,1.00,0.026667,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
23,0.0,1.0,0.142857,0.0,1.0,1.0,0.333333,0.333333,0.000000,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.00,0.75,0.75,0.25,0.75,1.00,0.000000,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
24,0.0,0.0,0.000000,1.0,0.0,1.0,0.000000,0.666667,0.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.75,0.50,0.25,0.00,0.00,1.00,0.026667,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
25,0.0,0.0,0.142857,0.0,0.0,1.0,0.000000,0.000000,0.666667,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.00,0.25,0.25,0.00,0.50,1.00,0.186667,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
26,0.0,1.0,0.000000,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.75,0.25,0.25,0.00,0.25,1.00,0.026667,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
27,0.0,1.0,0.000000,0.0,0.0,1.0,0.000000,0.000000,0.000000,0.0,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.25,0.25,0.75,0.25,0.75,0.00,0.053333,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
28,0.0,1.0,0.142857,0.0,1.0,0.0,0.000000,0.333333,0.000000,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,1.00,0.50,0.50,0.00,0.00,1.00,0.053333,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
29,0.0,1.0,0.142857,0.0,0.0,1.0,0.000000,0.333333,0.000000,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.75,0.75,1.00,1.00,1.00,1.00,0.213333,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
df.to_csv("dataset-normalizado.csv", index=False)
print(df.shape)